CREATE TABLE IF NOT EXISTS rooms (roomId TEXT PRIMARY KEY, name TEXT NOT NULL, phash TEXT);
CREATE TABLE IF NOT EXISTS users (userId TEXT PRIMARY KEY, alias TEXT NOT NULL, pubkey TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS roomMemberships(userId TEXT PRIMARY KEY NOT NULL, roomId TEXT NOT NULL, role INTEGER, FOREIGN KEY(userId) REFERENCES users(userId) ON DELETE CASCADE ,FOREIGN KEY(roomId) REFERENCES rooms(roomId) ON DELETE CASCADE );
CREATE TABLE IF NOT EXISTS sessions(userId TEXT PRIMARY KEY NOT NULL, onion TEXT NOT NULL, creationTime INT, FOREIGN KEY(userId) REFERENCES users(userId) ON DELETE CASCADE )
